FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
COPY yarn.lock ./
COPY . .

RUN yarn install --frozen-lockfile
RUN yarn build:api

FROM node:20-alpine AS runner

WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile --production

COPY --from=builder /app/dist/apps/api ./dist/apps/api

ENV PORT=4000
EXPOSE 4000

CMD ["node", "dist/apps/api/main.js"]
